name: Run Python Bengali Translator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install googletrans==4.0.0-rc1 gTTS

      - name: Run main.py
        run: python main.py "Please transfer 100 rupees to my account"

      - name: Upload Bengali MP3
        uses: actions/upload-artifact@v4
        with:
          name: bengali_output
          path: bengali_output.mp3
